### ISSUE TITLE
OpenWRT opkg submit build to repository please

### ISSUE THREAD

**Issue by aphorise** [rolandriegel/nload#16]
Kindly provide a PR to [github.com/openwrt/packages](https://github.com/openwrt/packages) in accordance to the OpenWRT build guide(s):

 - [Creating a package from your application](https://openwrt.org/docs/guide-developer/helloworld/chapter3)

My static make skills are not up to scratch and I struggled with the the proper static linking using an embedded device and OpenWRT that by default lacks a lot of the required ncurses or other dev / lib dependencies.

`nload` is a great match and would serve well in OpenWRT givens its network centric.

If a PR can be arrange then I dont mind helping to maintain it over time with new releases, etc.

Many thanks in advanced.

PS - also saw #15 after raising this which may be related.

**Comment by LXGMAX** [comment]
I have created a PR to openwrt/packages.
[https://github.com/openwrt/packages/pull/19638](https://github.com/openwrt/packages/pull/19638)

**Comment by LXGMAX** [comment]
Merged, this issue could be close.

**Comment by aphorise** [comment]
this has since been resolved in the latest OpenWRT version that are 22.03.5 or higher where `opkg install nload` works.
