### ISSUE TITLE
Auto-scale?

### ISSUE THREAD

**Issue by perguth** [rolandriegel/nload#19]
I would like `nload` to utilize the full height of the scale without setting hard values for `-u`.

But `-u H` just produces either a flat graph like so:

![image](https://github.com/rolandriegel/nload/assets/85259/18bb2618-58be-448e-8c1b-5ea4bf54881f)

Or on higher throughput a block like that:

![image](https://github.com/rolandriegel/nload/assets/85259/b39d1267-9526-49b7-8df3-e8947bf22217)

Is there way to make it react to current throughput?

***

Running with fixed unit and interval here: https://ygg.thingylabs.io/

**Comment by ahippo** [comment]
> I would like `nload` to utilize the full height of the scale without setting hard values for `-u`.

`nload` supports automatic scaling with `-i 0 -o 0` options.

> But `-u H` just produces either a flat graph like so:

`-u H` is for automatic selection of _units_ for bandwidth, not for scaling the graph itself.
(although `H` is for _bytes_ per second, which is an unusual unit for bandwidth)

Hope this helps.

**Comment by perguth** [comment]
Thank you for the response! It does not work for me:

I do end up with about the same graph for `nload` (on the left) and `nload -i 0 -o 0` (on the right):

![Screenshot 2024-04-17 10 52 18](https://github.com/rolandriegel/nload/assets/85259/a49ae892-c979-46ac-829f-46c92350459e)
(nload 0.7.4)

**Comment by ahippo** [comment]
> Thank you for the response! It does not work for me:
> 
> I do end up with about the same graph for `nload` (on the left) and `nload -i 0 -o 0` (on the right):
> ...
> (nload 0.7.4)


Ah, the version 0.7.4 is probably the reason.
Automatic scaling is only implemented on master branch in 4994d77b8644c697f3264a5d60e3e6149c4e0763 and is not present in 0.7.4.

**Comment by perguth** [comment]
Oh, I see! That works, thanks!

***

Sadly it has a rending problem when running in Gotty, https://github.com/yudai/gotty 

[Screen recording 2024-04-18 09.27.43.webm](https://github.com/rolandriegel/nload/assets/85259/44345855-0d7c-47d6-8c5c-e75b8abb05cd)

Running in a regular terminal seems fine though.
